### ISSUE TITLE
dokku pro early bird: what exactly am I getting?

### ISSUE THREAD

**Issue by opyate** [dokku/dokku-pro-issues#22]
### Description of feature

Dokku pro early bird: what exactly am I getting? Something similar to the "512 MiB 1 vCPU" entry-level DO Droplets? Or something more powerful?

![image](https://github.com/dokku/dokku-pro-issues/assets/96808/44ad3a39-6cf4-4ac5-bc2a-4070f3346bdc)

**Comment by josegonzalez** [comment]
You are getting software you install on your own machine. The software includes team management, an api, https-based pushed, and a dashboard. You would still need to bring your own machine (the one you install Dokku on) so you can install it wherever you prefer to do your hosting.
