### ISSUE TITLE
Dokku-pro Purchase Inquiry-20241223

### ISSUE THREAD

**Issue by ViViT123** [dokku/dokku-pro-issues#24]
### Description of feature

Hi team,

I hope my email finds you well. 
We have placed an order of Dokku Pro for our customer in 2022, and now they would like to use the latest version of Dokku Pro.
So I would like to know how to upgrade their license to the latest version?
And what's the price for upgrading? Could you please share with us a payment link?

Please see the end-user information below:
Name of Client: Li Auto Inc.
Email Address: xutao7@lixiang.com

Looking forward to hearing from you soon!
Best Regards,
ViVi

**Comment by josegonzalez** [comment]
Hi @ViViT123. I responded via email for this question. As Dokku Pro has a lifetime license, there are no fees for upgrades - you can continue using the license on the newer versions.

Please refer to our email chat for further details.

**Comment by ViViT123** [comment]
Hi Jose,
The customer of us who purchased dokku last year, and now they have a few questions regarding Dokku Pro, and we’d appreciate your support in clarifying the following points:

1、They noticed that Dokku recently released a Dokku Pro ARM version on the official website.
Do they need to purchase this version separately?
Is there an option to upgrade by paying the difference?
Or is it available for free to existing Dokku Pro users?
2、They would also like to change the administrator email associated with their current license.
Is it possible to update the registered email?
If not, they may consider purchasing a new license.
3、Regarding licensing:
It seems the current license limits the number of devices. Do you offer bulk licenses that support multiple devices?
If so, could you please share the pricing for bulk licensing options?
4、The customer is currently in urgent need of both the latest Dokku Pro versions for x86 and ARM.
Would it be possible to prioritize delivery of these versions?
If payment is required for access, please share the payment link and we will assist the customer with completing the transaction as soon as possible.

Thanks in advance for your support, and we look forward to your response!

Best regards,
ViVi

**Comment by josegonzalez** [comment]
I've reached out via email, we can continue our conversation there :)
