### ISSUE TITLE
Trial period

### ISSUE THREAD

**Issue by WooDeNDark** [dokku/dokku-pro-issues#6]
### Description of feature

According to the information provided, it is not entirely clear whether this product is necessary for me. It would be nice to make a trial period, for example, for 7 days, to understand all the pros and cons of the product.

**Comment by nikhila-naidu** [comment]
I would like to have a hands-on experience before purchasing a lifetime validity.

**Comment by josegonzalez** [comment]
If there is something I can provide instead - such as screenshots or screen recordings of usage - to show off what Dokku Pro is/provides, I'm happy to do so. I am not providing trial periods at this time.

**Comment by WooDeNDark** [comment]
It's a pity, since the only option I see is the possibility of test integration into my production architecture. Thanks for the answer.

**Comment by wanglong167** [comment]
@josegonzalez  screenshots

**Comment by nickreese** [comment]
@josegonzalez super interested in pro, just not enough information on it for me to make a decision compared to caprover. Even a brief video demo would be really useful.
